orbs:
  slack: circleci/slack@3.4.1
version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get install -y nodejs
            echo 'export PATH=/usr/bin:$PATH' >> $BASH_ENV
            which node && node -v
      - run: npm install
      - run: mkdir -p ~/reports/jest
      - run:
          name: Run tests
          command: npm test
      # - run: ./node_modules/.bin/codecov
      # - store_test_results:
      #     path: ~/reports
      # - store_artifacts:
      #     path: ~/reports
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml build --no-cache gsuite-wrapper
  eslint:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get install -y nodejs
            echo 'export PATH=/usr/bin:$PATH' >> $BASH_ENV
            which node && node -v
      - run: npm install
      - run: mkdir -p ~/reports
      - run: npm run lint -- --format junit --output-file ~/reports/eslint.xml
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
  yamllint:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: pip install yamllint
      - run: yamllint -d .yamllint.yml .
  docker-build-and-push:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get install -y nodejs
            echo 'export PATH=/usr/bin:$PATH' >> $BASH_ENV
            which node && node -v
      - run: npm install
      - run: npx semantic-release
      - run: docker build  --tag aegee/gsuite-wrapper:$(node -p "require('./package.json').version") --tag aegee/gsuite-wrapper:latest -f docker/Dockerfile .
      - run: docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
      - run: docker push aegee/gsuite-wrapper:$(node -p "require('./package.json').version")
      - run: docker push aegee/gsuite-wrapper:latest
      - slack/status:
          success_message: The Docker image for \`$CIRCLE_PROJECT_REPONAME\` with tags \`$(node -p "require('./package.json').version")\` and \`latest\` has been pushed to Dockerhub.
          failure_message: The Docker image for \`$CIRCLE_PROJECT_REPONAME\` build and push has failed.

workflows:
  version: 2
  test:
    jobs:
      - test
  eslint:
    jobs:
      - eslint
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  yamllint:
    jobs:
      - yamllint
  docker-build-and-push:
    jobs:
      - docker-build-and-push:
          filters:
            branches:
              only: master
