version: "3.4"

### Gsuite wrapper     #######################################
services:
  gsuite-wrapper:
    build:
      context: ./${PATH_GSUITE_WRAPPER}/..
      dockerfile: ./docker/Dockerfile
    image: aegee/gsuite-wrapper:dev
    #command: sh -c "sh /usr/app/scripts/bootstrap.sh && nodemon -L -e 'js,json' lib/run.js | bunyan --color"
    # volumes:
    #   - ./${PATH_GSUITE_WRAPPER}/../config/:/usr/app/src/config
    #   - ./${PATH_GSUITE_WRAPPER}/../lib/:/usr/app/src/lib
    #   - ./${PATH_GSUITE_WRAPPER}/../middlewares/:/usr/app/src/middlewares
    #   - ./${PATH_GSUITE_WRAPPER}/../migrations/:/usr/app/src/migrations
    #   - ./${PATH_GSUITE_WRAPPER}/../models/:/usr/app/src/models
    #   - ./${PATH_GSUITE_WRAPPER}/../scripts/:/usr/app/src/scripts
    #   - ./${PATH_GSUITE_WRAPPER}/../cli.js/:/usr/app/src/cli.js
