version: "3.4"

### GSUITE WRAPPER   #######################################
services:
  redis-gsuite-wrapper:
    restart: always
    image: redis:5-alpine
    volumes:
      - redis_gsuite_persistence:/data

  gsuite-wrapper:
    restart: on-failure
    image: aegee/gsuite-wrapper:latest
    links:
      - redis-gsuite-wrapper
    expose:
      - 8084
    volumes:
      - ./${PATH_GSUITE_WRAPPER}/../lib/config/myaegee-serviceaccount.json:/usr/app/src/lib/config/myaegee-serviceaccount.json
    environment:
      NODE_ENV: "${MYAEGEE_ENV}"
      #BUGSNAG_KEY: "${BUGSNAG_KEY_GSUITE_WRAPPER}"

volumes:
  redis_gsuite_persistence:
    driver: "local"

networks:
  default:
    external:
      name: OMS
